// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XPRTZ.BingeMachine.Shows.Database.Infrastructure;

#nullable disable

namespace XPRTZ.BingeMachine.Shows.Database.Infrastructure.Migrations
{
    [DbContext(typeof(ShowsDbContext))]
    [Migration("20231017101951_intialDb")]
    partial class intialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("XPRTZ.BingeMachine.Shows.Database.Infrastructure.Model.ShowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Premiered")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TvMazeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Show");
                });

            modelBuilder.Entity("XPRTZ.BingeMachine.Shows.Database.Infrastructure.Model.SyncInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("LastTvMazeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SyncInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
